# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer3',
        ),
    ]
